"""Initial commit

Revision ID: 3acb01c17785
Revises: 
Create Date: 2021-09-22 14:48:17.879453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3acb01c17785'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vilnius_weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('clouds', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_deg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vilnius_weather_data_dt'), 'vilnius_weather_data', ['dt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vilnius_weather_data_dt'), table_name='vilnius_weather_data')
    op.drop_table('vilnius_weather_data')
    # ### end Alembic commands ###
