"""Added sin and cos of hour and month

Revision ID: 6745c65109b6
Revises: 3acb01c17785
Create Date: 2021-09-22 16:36:22.380423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6745c65109b6'
down_revision = '3acb01c17785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vilnius_weather_data', sa.Column('hour_sin', sa.Float(), nullable=True))
    op.add_column('vilnius_weather_data', sa.Column('hour_cos', sa.Float(), nullable=True))
    op.add_column('vilnius_weather_data', sa.Column('month_sin', sa.Float(), nullable=True))
    op.add_column('vilnius_weather_data', sa.Column('month_cos', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vilnius_weather_data', 'month_cos')
    op.drop_column('vilnius_weather_data', 'month_sin')
    op.drop_column('vilnius_weather_data', 'hour_cos')
    op.drop_column('vilnius_weather_data', 'hour_sin')
    # ### end Alembic commands ###
